spring.datasource.password=admin
spring.datasource.username=root
spring.datasource.url=jdbc:mysql://localhost:3306/language_learning
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
#create
spring.jpa.database=mysql
spring.jpa.show-sql=false
chatbot.server.url=http://localhost:5000
